var _QUIZ=new Array(10);
_QUIZ[1]="DID YOU CHECK-IN / SCAN IN BAR CODE?";
_QUIZ[2]="DO YOU NEED HELP FOR ANY UPCOMING TEST/QUIZ IN SCHOOL?";
_QUIZ[3]="DO YOU NEED HELP WITH ANY CURRENT SCHOOL TOPIC?";
_QUIZ[4]="DID YOU BRING ANY HOMEWORK TO GET EXTRA HELP?";
_QUIZ[5]="REMINDER GIVEN TO STUDENT TO WAIT IN LOBBY & NOT TO GO OUTSIDE TILL YOU SEE YOUR GUARDIAN?";